import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home({ params }) {
	console.log('params::', params)

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>Main page</h1>
				<pre>
					Slug params: <br />
					{JSON.stringify(params.slug, null, 3)}
				</pre>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	)
}

export function getStaticPaths() {
	return {
		paths: [
			{ params: { slug: ['main'] } },
			{ params: { slug: ['se', 'main'] } },
			{ params: { slug: [] } },
		],
		fallback: false,
	}
}

export function getStaticProps({ params }) {
	return {
		props: {
			params,
		},
	}
}
